import{a as d,S as v,i as c}from"./assets/vendor-BLkLXWwN.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();d.defaults.baseURL="https://pixabay.com";function f(e,o,r){return d.get("/api/",{params:{key:"50262492-fe39fd1e0043f380ecc767a24",q:`${e}`,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:`${r}`,page:`${o}`}}).then(a=>a.data).catch(a=>{console.log(a)})}const h=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),S=new v(".gallery a",{captionsData:"alt",captionDelay:250});function $(e){return`<li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <ul class="stats">
        <li class="stats-item"><p class="stat-title">likes</p><p class="stat-value">${e.likes}</p></li>
        <li class="stats-item"><p class="stat-title">views</p><p class="stat-value">${e.views}</p></li>
        <li class="stats-item"><p class="stat-title">comments</p><p class="stat-value">${e.comments}</p></li>
        <li class="stats-item"><p class="stat-title">downloads</p><p class="stat-value">${e.downloads}</p></li>   
      </ul>
    </li>`}function q(){h.innerHTML=""}function P(){m.style.display="block"}function R(){m.style.display="none"}function E(){y.style.display="block"}function g(){y.style.display="none"}function L(e){h.insertAdjacentHTML("beforeend",e.map($).join("")),S.refresh()}const p=document.querySelector(".form"),O=document.querySelector(".load-more");let l=1,i=null;const n=15,A=1;p.addEventListener("submit",e=>{if(e.preventDefault(),i=new FormData(p).get("search-text"),!i){c.show({message:`Sorry, there are no images matching your search query. 
        Please try again!`,color:"red",position:"topRight"});return}l=A,q(),g(),P(),f(i,l,n).then(r=>{if(r.hits.length===0){w();return}l++,L(r.hits),console.log(r.totalHits-n),r.totalHits-n>0?E():b()}).catch(r=>{c.show({message:`Error: ${r}`,color:"red",position:"topRight"})}).finally(()=>{R(),p.reset()})});O.addEventListener("click",async e=>{e.preventDefault(),f(i,l,n).then(o=>{if(o.hits.length===0){w();return}console.log(o.totalHits-n*l),o.totalHits-n*l<0&&(g(),b()),L(o.hits),l++})});function b(){return c.show({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight"})}function w(){return c.show({message:`Sorry, there are no images matching your search query. 
        Please try again!`,color:"red",position:"topRight"})}
//# sourceMappingURL=index.js.map
