import{a as p,S as v,i}from"./assets/vendor-BLkLXWwN.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();p.defaults.baseURL="https://pixabay.com";const $=15;async function m(e,s){const{data:r}=await p.get("/api/",{params:{key:"50262492-fe39fd1e0043f380ecc767a24",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:$,page:s}});return r}const h=document.querySelector(".gallery"),y=document.querySelector(".load-more"),q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function P(e){return`<li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <ul class="stats">
        <li class="stats-item"><p class="stat-title">likes</p><p class="stat-value">${e.likes}</p></li>
        <li class="stats-item"><p class="stat-title">views</p><p class="stat-value">${e.views}</p></li>
        <li class="stats-item"><p class="stat-title">comments</p><p class="stat-value">${e.comments}</p></li>
        <li class="stats-item"><p class="stat-title">downloads</p><p class="stat-value">${e.downloads}</p></li>   
      </ul>
    </li>`}function R(){h.innerHTML=""}function g(e){const s=document.querySelector(`${e}`);s.style.display="block"}function L(e){const s=document.querySelector(`${e}`);s.style.display="none"}function E(){y.classList.remove("hidden")}function w(){y.classList.add("hidden")}function b(e){h.insertAdjacentHTML("beforeend",e.map(P).join("")),q.refresh()}const c=document.querySelector(".form"),O=document.querySelector(".load-more"),u=15;let a=1,n="";c.addEventListener("submit",B);O.addEventListener("click",A);function B(e){if(e.preventDefault(),n=new FormData(c).get("search-text").trim(),!n)return f();a=1,R(),w(),g(".loader"),setTimeout(async()=>{try{const r=await m(n,a,u);if(r.hits.length===0)return f();b(r.hits),S(r.totalHits),a++}catch(r){i.show({message:`Error: ${r}`,color:"red",position:"topRight"})}finally{L(".loader"),c.reset()}},200)}function A(){w(),g(".under-btn"),setTimeout(async()=>{try{const e=await m(n,a,u);b(e.hits),D(),S(e.totalHits),a++}catch(e){i.show({message:`Error: ${e}`,color:"red",position:"topRight"})}finally{L(".under-btn")}},200)}function S(e){a*u>=e?I():E()}function D(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function I(){i.show({message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight"})}function f(){i.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"})}
//# sourceMappingURL=index.js.map
